### ISSUE TITLE
360 support

### ISSUE THREAD

**Issue by pillowyfish98** [ChristopherJMiller/ArduinoGuitarHero#4]
not really an issue but im wondering if there is any code for this to work on the 360

**Comment by sanjay900** [comment]
If your 360 is modded, then yes
https://sanjay900.github.io/guitar-configurator/

**Comment by ChristopherJMiller** [comment]
Oh wow, cool to see another project tackling a similar problem space :)

No plan to support 360, but given [the reverse engineering work already done](https://sanjay900.github.io/guitar-configurator/controller-reverse-engineering/xbox-360-controllers.html) it shouldn't be too much additional work to change how the incoming UART packets are interpreted to support the signals the xbox controllers send.

Best of luck!
